# -*- makefile -*-
# vim: set filetype=make :
# Copyright 2012 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Embedded Controller firmware build system - common targets
#

BUILD_DIR := $(firstword $(subst /, ,$(out)))

# Create output directories if necessary
_common_dir_create := $(foreach d,$(common_dirs) $(common-dirs-y),\
	$(shell [ -d $(out)/$(d) ] || mkdir -p $(out)/$(d)))
_dir_create := $(foreach d,$(dirs) $(dirs-y),\
	$(shell [ -d $(out)/$(BLD)/$(d) ] || mkdir -p $(out)/RO/$(d); \
	    mkdir -p $(out)/RW/$(d)))

# V unset for normal output, V=1 for verbose output, V=0 for silent build
# (warnings/errors only). Use echo thus: $(call echo,"stuff  to  echo")
# Note: if cmd_* includes a $(MAKE) invocation, use the '+' prefix
# to inherit parallel make execution: "+$(call quiet,...)"
ifeq ($(V),0)
# V=0
Q := @
echo = echo -n;
quiet = echo -n; $(cmd_$(1))
silent = 1>/dev/null
silent_err = 2>/dev/null
MAKEFLAGS += --no-print-directory
else ifeq ($(V),)
# V=
Q := @
echo = echo $(1);
echo-cmd = $(if $(quiet_cmd_$(1)), \
		$(quiet_cmd_$(1)), \
		$(2) $(patsubst $(out)/%,%,$@))
quiet = @echo ' $(echo-cmd)' ; $(cmd_$(1))
silent = 1>/dev/null
silent_err = 2>/dev/null
MAKEFLAGS += --no-print-directory
else
# V=*
Q :=
echo = echo $(1);
quiet = $(cmd_$(1))
endif

# Provide an option to use a consistent ec_version.h file when
# compiling, which is useful to verify that a commit does not modify
# the resulting ec.bin
export STATIC_VERSION

# Commonly used compiler options used in these scripts
#
# -MT explicitly sets target file name in generated .d files to work around
#    a ccache issue.

# commands to build all targets
cmd_c_to_o = $(CC) -std=gnu11 $(C_WARN) $(C_WARN-$(CROSS_COMPILE_CC_NAME)) \
		$(CFLAGS) -MMD -MP -MF $@.d -c $< \
		-MT $(@D)/$(@F) -o $(@D)/$(@F)
cmd_c_to_s = $(CC) -S $(C_WARN) $(CFLAGS) $(C_WARN-$(CROSS_COMPILE_CC_NAME)) \
		-fno-lto -MMD -MP -MF $@.d -c $< \
		-MT $(@D)/$(@F) -o $(@D)/$(@F)
cmd_cxx_to_o = $(CXX) $(CFLAGS) $(CXXFLAGS) -MMD -MP -MF $@.d \
		      -c $< -MT $(@D)/$(@F) -o $(@D)/$(@F)
cmd_c_to_host = $(HOSTCC) $(HOST_CFLAGS) -MMD -MP -MF $@.d -MT $@ -o $@ \
	         $(sort $(foreach c,$($(*F)-objs),util/$(c:%.o=%.c)) $(wildcard $*.c)) $(HOST_LDFLAGS)
cmd_cxx_to_host = $(HOSTCXX) $(HOST_CXXFLAGS) \
		-MMD -MP -MF $@.d -MT $@ -o $@ \
		$(sort $(foreach c,$($(*F)-objs),util/$(c:%.o=%.cc)) $(wildcard $*.cc)) $(HOST_LDFLAGS)
cmd_o_to_a = $(AR) rcs $@ $^
# generate new version.h, compare if it changed and replace if so
cmd_version = ./util/getversion.sh > $@.tmp && \
	cmp -s $@.tmp $@ && rm -f $@.tmp || mv $@.tmp $@
cmd_mv_from_tmp = mv $(out)/$*.bin.tmp $(out)/$*.bin
cmd_copyrw-y = cd $(out) && cp RW/$(PROJECT).RW.flat RW/$(PROJECT).RW.bin

cmd_cp_script = cp "$<" "$@" && chmod +x "$@"
cmd_symlink_hdr = mkdir -p $(@D) && ln -srf $< $@
# If outputing to tty and column command exists, pipe into column.
# Otherwise, print in newline format.
cmd_pretty_print_cmd = @$(1) \
				| { [ -t 1 ]                         \
				    && which column 1>/dev/null 2>&1 \
				    && column || cat ; }
cmd_pretty_print_list = $(call cmd_pretty_print_cmd,echo $(1) | tr ' ' '\n')

.PHONY: utils-host
utils-host: $(host-utils) $(host-utils-cxx)

# Top-level target for host utility unit tests.
#
# This target serves as the entry point for running host-side utility unit tests
# during ebuilds and CQ runs.
#
# By default, `utils-test` depends on `utils-host` to ensure all necessary host
# binaries are compiled, but it does not execute any tests directly.
#
# To hook a new utility unit test into this flow, define a custom execution
# target in your utility's `build.mk` file and add it as a prerequisite
# dependency to `utils-test`. For example:
#
#   .PHONY: run-my_utility_test
#   run-my_utility_test: $(out)/util/my_utility_test
#   	@$(out)/util/my_utility_test
#
#   utils-test: run-my_utility_test
.PHONY: utils-test
utils-test: utils-host
	@echo "======= running host utility unit tests"

$(out)/%.bin: $(out)/%.obj
	$(call quiet,obj_to_bin,OBJCOPY)
	$(call quiet,copyrw-y,COPY_RW)
	$(call quiet,mv_from_tmp,MV     )

flat-y := $(out)/RW/$(PROJECT).RW.flat
flat-$(CONFIG_FW_INCLUDE_RO) += $(out)/RO/$(PROJECT).RO.flat

flat-$(CONFIG_DRAM_BASE) += $(out)/RW/$(PROJECT).RW.flat.dram

$(out)/RO/%.o.cmd:%.c
	$(file > $@,$(subst .o.cmd,.o,$(cmd_c_to_o)))
$(out)/RO/%.o:%.c
	$(call quiet,c_to_o,CC     )
$(out)/RW/%.o:%.c
	$(call quiet,c_to_o,CC     )

$(out)/RO/%.s:%.c
	$(call quiet,c_to_s,CC     )
$(out)/RW/%.s:%.c
	$(call quiet,c_to_s,CC     )

$(out)/RO/%.o:%.cc
	$(call quiet,cxx_to_o,CXX    )
$(out)/RW/%.o:%.cc
	$(call quiet,cxx_to_o,CXX    )

$(out)/RO/%.o:%.S
	$(call quiet,c_to_o,AS     )
$(out)/RW/%.o:%.S
	$(call quiet,c_to_o,AS     )

# Default rules for archives, dependencies need to be fixes in build.mk
$(out)/RO/%.a:
	$(call quiet,o_to_a,AR     )
$(out)/RW/%.a:
	$(call quiet,o_to_a,AR     )

# Conditionally force the rebuilding of ec_version.h only if it would be
# changed.
old_version_hash := $(shell cat $(out)/ec_version.h 2> /dev/null | md5sum -)
new_version_hash := $(shell BOARD=$(BOARD) ./util/getversion.sh | md5sum -)

ifneq ($(old_version_hash),$(new_version_hash))
.PHONY: $(out)/ec_version.h
endif

# All of the objects have an order only dependency on the ec_version header.
# This ensures that if ec_version.h needs to be built (because it was marked
# PHONY above) then it will be rebuilt before any objects.  This is important
# because some source files will include ec_version.h and fail to compile if
# it doesn't already exist.  This dependency shouldn't be a normal dependency
# because that would cause every object to be rebuilt when ec_version.h
# changes, instead of just the ones that actually depend on it.  The objects
# that truly depend on ec_version.h will have that information encoded in their
# .d file.
$(ro-objs): | $(out)/ec_version.h
$(rw-objs): | $(out)/ec_version.h

$(out)/ec_version.h:
	$(call quiet,version,VERSION)

# Symlink exported headers into $(out)/include/chromeos/ec/ so that host tools
# compiling against system libraries (e.g. libec) resolve <chromeos/ec/...>
# headers to the local checkout instead of /usr/include/chromeos/ec/.
chromeos-ec-headers := \
	$(out)/include/chromeos/ec/ec_commands.h \
	$(out)/include/chromeos/ec/ec_cmd_api.h \
	$(out)/include/chromeos/ec/panic_defs.h \
	$(out)/include/chromeos/ec/cros_ec_dev.h

$(out)/include/chromeos/ec/%: include/%
	$(call quiet,symlink_hdr,SYMLINK)

$(out)/include/chromeos/ec/cros_ec_dev.h: util/cros_ec_dev.h
	$(call quiet,symlink_hdr,SYMLINK)

$(host-utils): $(out)/%:$(host-srcs) | $(chromeos-ec-headers)
	$(call quiet,c_to_host,HOSTCC )

$(host-utils-cxx): $(out)/%:$(host-srcs-cxx) | $(chromeos-ec-headers)
	$(call quiet,cxx_to_host,HOSTCXX )

.PHONY: clean
clean:
	-rm -rf $(out) build/Makefile.sdk

.PHONY: clobber
clobber:
	-rm -rf build
ifneq ($(CCACHE),)
	$(CCACHE) -C
endif

.PHONY: help
help:
	@echo "Google Chromium EC build"
	@echo ""
	@echo "Common Targets:"
	@echo "  clean                - Clean build output"
	@echo "  clobber              - Clean all build output"
	@echo "  utils-host           - Build EC host utilities"
	@echo "  utils-test           - Build and run EC host utility unit tests"
	@echo ""
	@echo "Common Variables:"
	@echo "  V=1                  - Show make output"
	@echo "  STATIC_VERSION=1     - Force a constant version string for reproducable builds"
	@echo "  BUILDCC_PREFIX=      - Set the compiler prefix for the system doing "
	@echo "     the build (defaults to 'x86_64-pc-linux-gnu-')."
	@echo "  CROSS_COMPILE=       - Set the compiler for the board"
	@echo "  CROSS_COMPILE_arch=  - Set the compiler for arch"
	@echo "     The board picks its CROSS_COMPILE_arch if CROSS_COMPILE is not set."
	@echo "     arch may be one of 'arm', 'i386', 'nds32'."
	@echo "  HOST_CROSS_COMPILE=  - Set the compiler for the target platform on top of"
	@echo "     the EC. For example, this may be 32-bit x86 linux ('i686-pc-linux-gnu-'),"
	@echo "     64-bit x86 linux ('x86_64-pc-linux-gnu-'), or maybe 64-bit ARM linux"
	@echo "     ('aarch64-cros-linux-gnu-')."
	@echo "Example:"
	@echo "  make utils-host"

out_cros_ec_commands=build/kernel/include/linux/mfd/cros_ec_commands.h
.PHONY: build_cros_ec_commands
build_cros_ec_commands: $(out_cros_ec_commands)


$(out_cros_ec_commands): include/ec_commands.h util/make_linux_ec_commands_h.sh
	util/make_linux_ec_commands_h.sh $< $@

# Pull in special rules/targets for third_party software
-include third_party/rules.mk

.SECONDARY:

-include $(deps)

.PHONY: get_sdk
get_sdk:
ifneq ($(BAZEL_SUPPORTED),)
	declare -A toolchain_dict=($(shell ./util/coreboot_sdk.py)) ; \
	rm -rf build/Makefile.sdk ; \
	for key in "$${!toolchain_dict[@]}"; do \
		echo "export $${key} := $${toolchain_dict[$${key}]}" >> build/Makefile.sdk ; \
	done
	sync
endif
