/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef PLATFORM_EC_ZEPHYR_SHIM_INCLUDE_FPSENSOR_MATCHER_H_
#define PLATFORM_EC_ZEPHYR_SHIM_INCLUDE_FPSENSOR_MATCHER_H_

#define FP_ALGORITHM_TEMPLATE_SIZE CONFIG_FP_ALGORITHM_TEMPLATE_SIZE
#define FP_MAX_FINGER_COUNT CONFIG_FP_MAX_FINGER_COUNT

#endif /* PLATFORM_EC_ZEPHYR_SHIM_INCLUDE_FPSENSOR_MATCHER_H_ */
