# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# C1NV board-specific Kconfig settings.

CONFIG_BOARD_C1NV=y
CONFIG_GOOGLE_PRIVATE=y

# Battery
CONFIG_PLATFORM_EC_BATTERY_REPLACE_NULLS=n

# Clock
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=20000000

# Uart
CONFIG_UART_NPCX_USE_MDMA=y
