# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# meru board-specific Kconfig settings.

CONFIG_BOARD_MERU=y

# Detachable
CONFIG_PLATFORM_EC_DETACHABLE_BASE=y
CONFIG_PLATFORM_EC_BASE_ATTACHED_SWITCH=y
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y

# Clock
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=25000000

# Uart
CONFIG_UART_NPCX_USE_MDMA=y

# External Power
CONFIG_PLATFORM_EC_EXTPOWER_GPIO_CUSTOM=y

# Battery
CONFIG_PLATFORM_EC_BATTERY_REPLACE_NULLS=n
CONFIG_PLATFORM_EC_SMBUS_PEC=y
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10

# CBI
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y

# System Lock
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Disable Hibernate since exit is unreliable b/489415249
CONFIG_PLATFORM_EC_HIBERNATE=n

# Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=y
CONFIG_PLATFORM_EC_BUTTON_TRIGGERED_RECOVERY=y
