/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef PLATFORM_EC_ZEPHYR_TEST_PROCHOT_VCMP_INCLUDE_TEST_VCMP_SENSOR_H_
#define PLATFORM_EC_ZEPHYR_TEST_PROCHOT_VCMP_INCLUDE_TEST_VCMP_SENSOR_H_

#define SENSOR_ATTR_UPPER_VOLTAGE_THRESH 0
#define SENSOR_ATTR_LOWER_VOLTAGE_THRESH 1

#endif /* PLATFORM_EC_ZEPHYR_TEST_PROCHOT_VCMP_INCLUDE_TEST_VCMP_SENSOR_H_ */
